More unit tests
aniehuser/senior-design-group10 pull request #119
Opened 2019-04-03 19:02 UTC by clundin55

2019-04-05 20:24 UTC, aniehuser commented on yw_website/yw_website/apps/website/tests.py
> +    def test_view_my_workflows_authenticated(self):
these sanity tests are good

2019-04-05 20:25 UTC, aniehuser commented on yw_website/yw_website/apps/website/tests.py
> +        self.client.logout()
this might effect other tests that require authenticated client, you should create a new client object instead of logging out this one

2019-04-05 20:26 UTC, aniehuser commented on yw_website/yw_website/apps/website/views.py
> +    workflow_list = workflow_list.filter(user=request.user)
gracias

2019-04-05 20:27 UTC, aniehuser commented on yw_website/yw_website/apps/website/tests.py
> +        response = self.client.post(route, self.data, format="json")
no need to have `route` or e`response` in the setup i dont think

2019-04-05 20:28 UTC, aniehuser commented on yw_website/yw_website/apps/website/tests.py
> +                                                        "redirected to login after trying to access my_workflows page")
new line

2019-04-05 20:29 UTC, aniehuser commented on yw_website/yw_website/apps/website/tests.py
> +        self.client.logout()
> you should create a new client object

and make sure that the new client object is logged out

2019-04-05 20:30 UTC, aniehuser requested changes
The main problem is you log out the client in a method, other than that just some trivial suggestions

2019-04-05 21:51 UTC, clundin55 commented
@aniehuser applied your feedback

2019-04-08 02:36 UTC, aniehuser commented on yw_website/yw_website/apps/website/tests.py
> +        client.credentials(HTTP_AUTHORIZATION='Token {}'.format(self.token))
just an fyi, you only need to do this token authentication for the rest requests, accessing pages only requires like you are doing here uses session authentication, so adding a token HTTP_AUTHORIZATION is effectively doing nothing in this context

2019-04-08 02:38 UTC, aniehuser commented on yw_website/yw_website/apps/website/tests.py
> +        res = client.post('/rest-auth/login/', data={'username': username, 'password': password},
we're testing an unauthenticated client, so  we shouldn't log in. that's tested in the above test

2019-04-09 02:43 UTC, clundin55 commented
@aniehuser got rid of unneeded client auth stuff in the unauthenticated my workflows test

2019-04-09 04:24 UTC, aniehuser approved these changes

2019-04-09 04:24 UTC, merged