Added test for recieving workflow from client. Added test for databas…
aniehuser/senior-design-group10 pull request #32
Opened 2018-12-06 21:29 UTC by clundin55

…e API

2018-12-06 22:48 UTC, aniehuser commented on yw_website/yw_rest_services/tests.py
> +        self.user = User.objects.create_user(username='testuser', password='12345')
do these tests work if run more than once? usernames are supposed to be unique in our database, so you should generate a unique username each time. Look at [this link](https://docs.python.org/3/library/uuid.html) for reference on how to do this

2018-12-06 22:50 UTC, aniehuser commented on yw_website/yw_db/tests.py
> +        test = Workflow.objects.create(pk=1)
again, does this test work if run more than once? would it work if there were other tests that created a workflow of id 1? You should create the workflow object to ensure that it is unique and does not collide with other database values.

2018-12-06 22:52 UTC, aniehuser commented on yw_website/yw_db/tests.py
> +from yw_db.models import Workflow
Are we using a test database for this or do these tests get run using the actual database?

2018-12-06 22:52 UTC, aniehuser requested changes
look at above questions

2018-12-07 00:30 UTC, clundin55 commented
@aniehuser django creates and tears down a temporary test database when the test command is run.

2018-12-07 05:33 UTC, aniehuser commented on yw_website/yw_rest_services/tests.py
> +        self.user = User.objects.create_user(username='testuser', password='12345')
Even if a new test database is created every every time test is run, if there are other tests that are created later where somebody else also creates a user with username `testuser`, we could get poor or inconsistent test results

2018-12-07 05:36 UTC, aniehuser commented
> django creates and tears down a temporary test database when the test command is run.

thank god that makes our lives a lot easier

2018-12-07 05:37 UTC, aniehuser commented on yw_website/yw_db/tests.py
> +        test = Workflow.objects.create(pk=1)
since workflow id auto-increments I still think it is a bad idea to hardcode in an id.

2018-12-10 20:14 UTC, clundin55 commented
@aniehuser fixed potential collisions

2018-12-11 00:32 UTC, aniehuser commented
@clundin55 you still need to implement a uuid for the username mentioned in [this review](https://github.com/aniehuser/senior-design-group10/pull/32#pullrequestreview-182485606). Other than that, this LGTM!

2018-12-21 16:28 UTC, clundin55 commented
@aniehuser added uuid username

2018-12-24 04:17 UTC, aniehuser commented on yw_website/yw_rest_services/tests.py
> +        username = str(uuid.uuid1())
lets remember to always use uuid v1 for any other tests we might run.

2018-12-24 04:18 UTC, aniehuser approved these changes

2018-12-24 04:18 UTC, merged