Fixed scripts for deploying and an error in creating mock db
aniehuser/senior-design-group10 pull request #45
Opened 2019-01-31 06:52 UTC by clundin55

Forgot to add database migrations for website app. Need this merged to have a clean install run.

2019-01-31 09:54 UTC, aniehuser commented on scripts/deploy_python.sh
> +python3 manage.py migrate website
should be just `python` for mackenzie

2019-01-31 09:55 UTC, aniehuser commented on scripts/remote_deploy_python.sh
> +python3 manage.py migrate website
same, should be just `python`

2019-01-31 10:04 UTC, aniehuser requested changes
was wondering what why that broke

2019-01-31 18:32 UTC, clundin55 commented on scripts/deploy_python.sh
> +python3 manage.py migrate website
fixed

2019-01-31 18:32 UTC, clundin55 commented on scripts/remote_deploy_python.sh
> +python3 manage.py migrate website
fixed

2019-01-31 18:33 UTC, clundin55 commented
> was wondering what why that broke

@aniehuser The app code was separated from the website code. So the database of the app is separate so it needs it's own database migrations.

2019-02-01 01:29 UTC, aniehuser approved these changes

2019-02-01 01:29 UTC, aniehuser commented
Interesting, well I tested it and it works so lets get this merged

2019-02-01 01:29 UTC, merged